### ISSUE TITLE
Doesn't compile: #include "pin_magic.h" not found.

### ISSUE THREAD

**Issue by zoomx** [JoaoLopesF/SPFD5408#1]
In SPFD5408_Adafruit_TFTLCD.cpp there is a #include "pin_magic.h"  but there isn't such file.
I changed the include to #include "pin_magic_UNO.h" but maybe it's better to add it from the original library.

**Comment by JoaoLopesF** [comment]
Hi, For any reason, the incomplete code is published, I yet testing a version with one pin_magic.
I fixed it, please test.

Regards
Joao

**Comment by zoomx** [comment]
Thanks Joao! Now it compiles flawless.

**Comment by JoaoLopesF** [comment]
Hi,

Thanks for your contribution

I put a new version now, please test it.

Now works in uno mega and leonardo
And few ajusts

Regards

Joao
Em 29/07/2015 17:59, "zoomx" notifications@github.com escreveu:
