### ISSUE TITLE
Could I get some help porting this to the Arduino Due?

### ISSUE THREAD

**Issue by differentprogramming** [JoaoLopesF/SPFD5408#10]
I have lots of programming experience but no Arduino knowledge, I could use some help.

**Comment by JoaoLopesF** [comment]
Hi, Sorry delay too long to answer.

Sorry but this library is only to UNO or Mega.
For another boards I am working with Nextion TFT, 
It is a excellent solution, 3v3 compatible and only 4 wires :-)

Regards

Joao
