### ISSUE TITLE
TouchScreen doesn't seem to be working with Arduino Leonardo

### ISSUE THREAD

**Issue by varunkumar** [JoaoLopesF/SPFD5408#19]
I am unable to get the touchscreen working with Arduino Leonardo. Tried examples. Nothing happens when I touch the screen.

**Comment by JoaoLopesF** [comment]
Hi, Don't have any know incompatibility to Leonardo.
You have a regular Uno to make a test ?

Regards
Joao

Joao

**Comment by varunkumar** [comment]
Yes, I have an Uno. I will test it with that.
