### ISSUE TITLE
Some performance tweaks

### ISSUE THREAD

**Issue by RobTillaart** [JoaoLopesF/SPFD5408#2]
Hi,

Did some investigation on your code based upon a question on the Arduino forum.
Came up with some performance tweaks. If you are interested please check:
- http://forum.arduino.cc/index.php?topic=351058.msg2420805#msg2420805 -

regards,
Rob

**Comment by JoaoLopesF** [comment]
Hi,

Sorry for delay
I will evaluate this
Thanks for your contribute
Joao
