### ISSUE TITLE
ID 0x4040

### ISSUE THREAD

**Issue by doleron** [JoaoLopesF/SPFD5408#26]
Hello, Joao. Like you I also tried several libraries and all of them failed on the examples. Your lib at least printed something in the screen (see this output from spfd5408_graphicstest https://www.youtube.com/watch?v=Baw-jCqco-s) So I hope to find a solution here. I found that my controller ID is 0x4040 and not sure how compatible yet. How can I change your Library to make it compatible?

**Comment by JoaoLopesF** [comment]
Sorry, this library is discontinued, due now few TFT is SPFD5402, so few TFT is works with it.
I now use the Nextion Display instead this TFT
