### ISSUE TITLE
Inverse colors

### ISSUE THREAD

**Issue by maitredede** [JoaoLopesF/SPFD5408#3]
Hi,

When trying samples my color are inversed (red is cyan, black is white...)

In my app, I have to inverse all color bits to get the right colors :)

**Comment by JoaoLopesF** [comment]
Hi,

Please modify the SPFD5408_Adafruit_TFTLCD line 307

before:

```
// *** SPFD5408 change -- Begin
// Not tested yet
//writeRegister8(ILI9341_INVERTOFF, 0);
//delay(500);
```

after:

```
// *** SPFD5408 change -- Begin
// Not tested yet
writeRegister8(ILI9341_INVERTOFF, 0);
//delay(500);
```

**Comment by rohanraut92** [comment]
Im getting 2 half screens. Idk how to resolve it.

**Comment by tsvelichkov** [comment]
i had to use this to fix my inverted colors:
writeRegister8(ILI9341_INVERTON, 0);

this is commented
//writeRegister8(ILI9341_INVERTOFF, 0);

This fixed the color issue on my LCD

**Comment by nopnop2002** [comment]
Hello manniakk.
Your TFT controller is NOT SPFD5408.
It's ILI9342.


https://forum.arduino.cc/index.php?topic=473885.0

**Comment by Mark42XLII** [comment]
In my case, pure colors and secondary colors kinda work fine, but the other colors and black always are weird. Like, black looks like purple.

**Comment by nopnop2002** [comment]
Hello manniakk.
Try this.
https://github.com/prenticedavid/MCUFRIEND_kbv/tree/master/examples/LCD_ID_readreg
You can see your tft driver.
