### ISSUE TITLE
Mirrored text

### ISSUE THREAD

**Issue by RafaEspG** [JoaoLopesF/SPFD5408#9]
First, thanks for the code, and an apology for my bad english.

It work very fine (the touch screen and colors, works fine in Arduino Mega 2560) but i have a problem when im using "tft.setRotation(1);" , the text is mirrored and coordinates of the drawings too, and i can´t fix this.

Can you help me, please?

**Comment by nopnop2002** [comment]
Perhaps Your TFT controller is NOT SPFD5408.
It's ILI9342.

https://forum.arduino.cc/index.php?topic=473885.0

**Comment by JoaoLopesF** [comment]
HI, in line 309 of SPFD5408_Adafruit_TFTLCD.cpp, try uncomment this lines:
        // *** SPFD5408 change -- Begin
	// Not tested yet
	//writeRegister8(ILI9341_INVERTOFF, 0);
	//delay(500);
Regards
Joao

**Comment by wkyong** [comment]
I am using your library for my 2.8inch TFT screen from MCUfriend. I manage to get it to display the program using identifier ID 0x7575. However I find the text all mirrored. I had tried to add in the code 0x16, 0x08 to set the MY, MX and MV to 0, 0, 0 but failed. I am not able to find which code actually inverted the screen. Supplier of this screen claim they use a SPFD 5408 controller which lead me to this library. Please help me by providing some insight on which code I should change to rectify this problem.

**Comment by wkyong** [comment]
I had my problem solved. Upon checking the lcd ID, it shows 4747 which link to HX8437D lcd controller. By using the correct library the TFT screen works flawlessly.

**Comment by marcudanf** [comment]
@wkyong I have the same issue, can you please send a link to that library??
